services:
  mysql:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    container_name: mysql
    restart: always
    ports:
      - 3010:3306
    environment:
      MYSQL_ROOT_PASSWORD: "135689Javana@"
      MYSQL_DATABASE: "jv"
      MYSQL_USER: "JAEVERBA"
      MYSQL_PASSWORD: "135689Javana@"
    volumes:
      - ./mysql/mysql-data:/var/lib/mysql
    networks:
      mysql_network:
        aliases:
          - mysql_host

volumes:
  schemas: {}

networks:
  mysql_network:
    name: mysql_net
    driver: bridge




#  mysql:
#    image: mysql:8
#    command: --default-authentication-plugin=mysql_native_password
#    environment:
#      MYSQL_DATABASE: jv
#      MYSQL_ROOT_PASSWORD: 135689Javana@
#    volumes:
#     - ./mysql-data:/var/lib/mysql